on:  
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_for_platforms:    
    uses: ./.github/actions/godot/action.yml
    # Using a strategey matrix like this will allow us to simply specify the configuration for future build targets without having to rewrite them
    strategy:
      matrix:
        include:
          - target: "Windows Desktop"
            output_path: Poo_Farmer_win.exe
          - target: "Linux/X11"
            output_path: Poo_Farmer_linux.x86_64
    with: 
      target_name: ${{ matrix.target }}
      output_path: ${{ matrix.output_path }}

