name: Windows Build

on:
  #push:
  #  branches:
  #    - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows_build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Windows Build
    steps:
      - uses: actions/checkout@v2

      - name: Install Godot
        uses: paulloz/godot-action@v1.2
        with:
          version: 3.5.1
          mono: true          
      
      - name: Build Godot for Windows
        run: |
          mkdir ${{ github.workspace }}/build/
          godot --path poofarmer --export "Windows Desktop" ${{ github.workspace }}/build/Poo_Farmer_win.exe -v